/**
 * Intelligence page — ATT&CK technique overview from recent detections.
 *
 * IMPORTANT: ATT&CK mappings come ONLY from the backend.
 * The frontend does NOT create heuristics that infer ATT&CK techniques.
 *
 * Clearly distinguishes:
 * - MODEL CLASSIFICATION (what the ML model predicted)
 * - ATT&CK MAPPING (which techniques are potentially applicable)
 */

import { useEffect, useState, useCallback } from 'react';
import { useAppContext } from '@/hooks/useAppContext';
import type { ATTACKMapping } from '@/api/types';

interface TechniqueAggregate {
  technique_id: string;
  technique_name: string;
  tactic: string;
  qualification: string;
  count: number;
  rationale: string;
}

export function Intelligence() {
  const { api } = useAppContext();
  const [techniques, setTechniques] = useState<TechniqueAggregate[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchData = useCallback(async () => {
    if (!api) return;
    try {
      const res = await api.getEvents({ limit: 50, offset: 0 });
      const techniqueMap = new Map<string, TechniqueAggregate>();

      for (const event of res.events ?? []) {
        const meta = event.metadata ?? {};
        const explanation = meta['explanation'] as Record<string, unknown> | undefined;
        const mappings = (explanation?.['attack_mappings'] ?? meta['attack_mappings'] ?? []) as ATTACKMapping[];

        for (const m of mappings) {
          const existing = techniqueMap.get(m.technique_id);
          if (existing) {
            existing.count++;
          } else {
            techniqueMap.set(m.technique_id, {
              technique_id: m.technique_id,
              technique_name: m.technique_name,
              tactic: m.tactic,
              qualification: m.qualification,
              count: 1,
              rationale: m.rationale,
            });
          }
        }
      }

      setTechniques(
        Array.from(techniqueMap.values()).sort((a, b) => b.count - a.count),
      );
      setError(null);
    } catch {
      setError('Failed to load intelligence data');
    } finally {
      setLoading(false);
    }
  }, [api]);

  useEffect(() => { fetchData(); }, [fetchData]);

  if (loading) {
    return <div className="state-message" role="status"><div className="state-message__title">Loading…</div></div>;
  }

  if (error) {
    return (
      <div className="state-message">
        <div className="state-message__title">Error</div>
        <div className="state-message__text">{error}</div>
      </div>
    );
  }

  return (
    <div>
      <div className="page-header">
        <h1 className="page-title">THREAT INTELLIGENCE</h1>
      </div>

      <div style={{
        padding: 'var(--space-4)',
        background: 'rgba(255, 255, 255, 0.02)',
        border: '1px solid rgba(255, 255, 255, 0.1)',
        borderRadius: '4px',
        fontSize: 'var(--font-size-sm)',
        color: 'var(--text-muted)',
        marginBottom: 'var(--space-6)',
        maxWidth: '800px',
        lineHeight: 1.6
      }}>
        <strong style={{ color: 'var(--text-primary)' }}>ATT&CK CONTEXT — LATEST 50 DETECTIONS.</strong><br/>
        Mappings are derived from backend ML classification and ATT&CK mapping engine.
        These are contextual associations, not proof that a technique occurred.
      </div>

      {techniques.length === 0 ? (
        <div className="state-message">
          <div className="state-message__title">No ATT&CK intelligence available</div>
          <div className="state-message__text">
            No ATT&CK intelligence available. Technique mappings are generated by the backend when threat classifications produce applicable associations.
          </div>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-4)' }}>
          {techniques.map(t => {
            const qualClass = t.qualification === 'likely'
              ? 'attack-card__qualification--likely'
              : t.qualification === 'observed indicators consistent with'
                ? 'attack-card__qualification--observed'
                : 'attack-card__qualification--possible';

            return (
              <div key={t.technique_id} className="card" style={{ padding: 'var(--space-5)', borderLeft: '4px solid var(--accent-primary)' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 'var(--space-3)' }}>
                  <div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-3)', marginBottom: 'var(--space-2)' }}>
                      <span style={{ color: 'var(--accent-primary)', fontWeight: 600, fontFamily: 'var(--font-mono)' }}>{t.technique_id}</span>
                      <h3 style={{ margin: 0, fontSize: 'var(--font-size-lg)', color: 'var(--text-primary)' }}>{t.technique_name}</h3>
                    </div>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--space-3)', alignItems: 'center' }}>
                      <span className="badge badge--threat">{t.tactic}</span>
                      <span className={`attack-card__qualification ${qualClass}`} style={{ fontSize: 'var(--font-size-xs)' }}>
                        {t.qualification.toUpperCase()}
                      </span>
                    </div>
                  </div>
                  <div style={{
                    fontFamily: 'var(--font-mono)',
                    fontSize: 'var(--font-size-xl)',
                    color: 'var(--text-primary)',
                    fontWeight: 700,
                    background: 'rgba(255, 255, 255, 0.05)',
                    padding: 'var(--space-2) var(--space-4)',
                    borderRadius: '4px'
                  }}>
                    {t.count}
                    <span style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)', display: 'block', textAlign: 'center', fontWeight: 'normal' }}>
                      DETECTION{t.count !== 1 ? 'S' : ''}
                    </span>
                  </div>
                </div>
                
                <div style={{
                  marginTop: 'var(--space-4)',
                  padding: 'var(--space-3)',
                  background: 'rgba(0, 0, 0, 0.2)',
                  borderRadius: '4px',
                  border: '1px solid rgba(255, 255, 255, 0.05)',
                  fontSize: 'var(--font-size-sm)',
                  color: 'var(--text-secondary)',
                  lineHeight: 1.5
                }}>
                  <div style={{ fontSize: 'var(--font-size-xs)', textTransform: 'uppercase', color: 'var(--text-muted)', marginBottom: 'var(--space-1)', letterSpacing: '0.05em' }}>Rationale</div>
                  {t.rationale}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
